-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS ${SCHEMA}.titles
(
    id          smallint               NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 1000 CACHE 1 ),
    name        character varying(100) NOT NULL,
    description text,
    CONSTRAINT pk_titles PRIMARY KEY (id),
    CONSTRAINT uc_title_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.programs
(
    id          smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 1000 CACHE 1 ),
    title_id    smallint,
    subtitle_id smallint,
    name        character varying(100),
    CONSTRAINT pk_programs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.sub_programs
(
    id         smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 10000 CACHE 1 ),
    program_id smallint NOT NULL,
    name       character varying(100),
    CONSTRAINT pk_sub_programs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.payments
(
    id                        bigint               NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 1000000 CACHE 1 ),
    title_id                  smallint,
    subtitle_id               smallint,
    program_id                smallint,
    sub_program_id            smallint,
    sub_sub_program_id        smallint,
    practice_category_id      smallint,
    state_code                character varying(2) NOT NULL,
    year                      smallint             NOT NULL,
    payment                   numeric(14, 2),
    recipient_count           bigint,
    base_acres                numeric(10, 2),
    farm_count                bigint,
    contract_count            bigint,
    premium_policy_count      bigint,
    liability_amount          bigint,
    premium_amount            bigint,
    premium_subsidy_amount    bigint,
    indemnity_amount          bigint,
    farmer_premium_amount     bigint,
    loss_ratio                numeric,
    net_farmer_benefit_amount bigint,
    practice_code             character varying(100),
    practice_code_variant     character varying(100),
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT uc_payments UNIQUE (title_id, subtitle_id, program_id, sub_program_id, state_code, year)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.payments_by_counties
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 1000000 CACHE 1 ),
    title_id smallint,
    subtitle_id smallint,
    program_id smallint,
    sub_program_id smallint,
    sub_sub_program_id smallint,
    practice_category_id smallint,
    county_fips_code character varying(5) NOT NULL,
    year smallint NOT NULL,
    payment numeric(14, 2),
    recipient_count bigint,
    base_acres numeric(10, 2),
    farm_count bigint,
    contract_count bigint,
    premium_policy_count bigint,
    liability_amount bigint,
    premium_amount bigint,
    premium_subsidy_amount bigint,
    indemnity_amount bigint,
    farmer_premium_amount bigint,
    loss_ratio numeric,
    net_farmer_benefit_amount bigint,
    practice_code character varying(100),
    practice_code_variant character varying(100),
    CONSTRAINT pk_payments_by_counties PRIMARY KEY (id),
    CONSTRAINT uc_payments_by_counties UNIQUE (title_id, subtitle_id, program_id, sub_program_id, year, county_fips_code)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.states
(
    code character varying(2)   NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT pk_states PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.subtitles
(
    id       smallint               NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 1000 ),
    title_id smallint               NOT NULL,
    name     character varying(100) NOT NULL,
    CONSTRAINT pk_subtitles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.counties
(
    fips_code character varying(5) NOT NULL,
    state_code character varying(2) NOT NULL,
    name character varying(100) NOT NULL,
    remarks character varying(100),
    CONSTRAINT pk_counties_fips_code PRIMARY KEY (fips_code)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.practice_categories
(
    id                    smallint          NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 1000 ),
    name                  character varying NOT NULL,
    display_name          character varying,
    category_grouping     character varying,
    program_id            smallint          NOT NULL,
    is_statutory_category boolean           NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ${SCHEMA}.practices
(
    code         character varying(100) NOT NULL,
    name         character varying(200) NOT NULL,
    display_name character varying(200),
    source       character varying,
    CONSTRAINT pk_practices PRIMARY KEY (code)
);

COMMENT ON TABLE ${SCHEMA}.practices
    IS 'Conservation Practice Standards';

CREATE TABLE IF NOT EXISTS ${SCHEMA}.sub_sub_programs
(
    id             smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 10000 ),
    sub_program_id smallint NOT NULL,
    name           character varying(100),
    CONSTRAINT pk_sub_sub_programs PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS ${SCHEMA}.programs
    ADD CONSTRAINT "fk_ titles_id" FOREIGN KEY (title_id)
        REFERENCES ${SCHEMA}.titles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.programs
    ADD CONSTRAINT "fk_ subtitles_id" FOREIGN KEY (subtitle_id)
        REFERENCES ${SCHEMA}.subtitles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.sub_programs
    ADD CONSTRAINT fk_programs_id FOREIGN KEY (program_id)
        REFERENCES ${SCHEMA}.programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_programs_id FOREIGN KEY (program_id)
        REFERENCES ${SCHEMA}.programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_sub_programs_id FOREIGN KEY (sub_program_id)
        REFERENCES ${SCHEMA}.sub_programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_states_id FOREIGN KEY (state_code)
        REFERENCES ${SCHEMA}.states (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_titles_id FOREIGN KEY (title_id)
        REFERENCES ${SCHEMA}.titles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_subtitles_id FOREIGN KEY (subtitle_id)
        REFERENCES ${SCHEMA}.subtitles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_practice_categories_id FOREIGN KEY (practice_category_id)
        REFERENCES ${SCHEMA}.practice_categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_practice_code FOREIGN KEY (practice_code)
        REFERENCES ${SCHEMA}.practices (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments
    ADD CONSTRAINT fk_sub_sub_programs_id FOREIGN KEY (sub_sub_program_id)
        REFERENCES ${SCHEMA}.sub_sub_programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.subtitles
    ADD CONSTRAINT fk_titles_id FOREIGN KEY (title_id)
        REFERENCES ${SCHEMA}.titles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.practice_categories
    ADD CONSTRAINT fk_program_id FOREIGN KEY (program_id)
        REFERENCES ${SCHEMA}.programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.sub_sub_programs
    ADD CONSTRAINT fk_sub_programs_id FOREIGN KEY (sub_program_id)
        REFERENCES ${SCHEMA}.sub_programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

ALTER TABLE IF EXISTS ${SCHEMA}.counties
    ADD CONSTRAINT fk_counties_state_code FOREIGN KEY (state_code)
    REFERENCES ${SCHEMA}.states (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_programs_id FOREIGN KEY (program_id)
    REFERENCES ${SCHEMA}.programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_titles_id FOREIGN KEY (title_id)
    REFERENCES ${SCHEMA}.titles (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_states_id FOREIGN KEY (county_fips_code)
    REFERENCES ${SCHEMA}.counties (fips_code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_subtitles_id FOREIGN KEY (subtitle_id)
    REFERENCES ${SCHEMA}.subtitles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_sub_programs_id FOREIGN KEY (sub_program_id)
    REFERENCES ${SCHEMA}.sub_programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_sub_sub_programs_id FOREIGN KEY (sub_sub_program_id)
    REFERENCES ${SCHEMA}.sub_sub_programs (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_practice_categories_id FOREIGN KEY (practice_category_id)
    REFERENCES ${SCHEMA}.practice_categories (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_practices_code FOREIGN KEY (practice_code)
    REFERENCES ${SCHEMA}.practices (code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.payments_by_counties
    ADD CONSTRAINT fk_payments_by_counties_counties_fips_code FOREIGN KEY (county_fips_code)
    REFERENCES ${SCHEMA}.counties (fips_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


-- International commodity market data (USDA FAS PSD long-format source)

CREATE TABLE IF NOT EXISTS ${SCHEMA}.countries
(
    code      character varying(3)   NOT NULL,
    name      character varying(100) NOT NULL,
    api_code  character varying(3),
    region    character varying(50),
    is_active boolean                NOT NULL DEFAULT true,
    CONSTRAINT pk_countries PRIMARY KEY (code),
    CONSTRAINT uc_countries_api_code UNIQUE (api_code)
);

COMMENT ON COLUMN ${SCHEMA}.countries.api_code
    IS 'Code exposed in API responses when it differs from the PSD code, for example CH becomes CN for China';

CREATE TABLE IF NOT EXISTS ${SCHEMA}.commodities
(
    code           character varying(10)  NOT NULL,
    name           character varying(150) NOT NULL,
    api_slug       character varying(50)  NOT NULL,
    bushels_per_mt numeric(12, 6),
    parent_code    character varying(10),
    CONSTRAINT pk_commodities PRIMARY KEY (code),
    CONSTRAINT uc_commodity_api_slug UNIQUE (api_slug)
);

COMMENT ON COLUMN ${SCHEMA}.commodities.bushels_per_mt
    IS 'Per-commodity bushel conversion factor, NULL when bushels do not apply';

CREATE TABLE IF NOT EXISTS ${SCHEMA}.market_attributes
(
    id               smallint               NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 10000 CACHE 1 ),
    psd_attribute_id character varying(10)  NOT NULL,
    name             character varying(100) NOT NULL,
    metric_key       character varying(50)  NOT NULL,
    include_in_api   boolean                NOT NULL DEFAULT false,
    CONSTRAINT pk_market_attributes PRIMARY KEY (id),
    CONSTRAINT uc_market_attributes_psd_id UNIQUE (psd_attribute_id)
);

COMMENT ON TABLE ${SCHEMA}.market_attributes
    IS 'PSD Attribute_Id lookup, metric_key maps source attributes onto API field names';

CREATE TABLE IF NOT EXISTS ${SCHEMA}.measurement_units
(
    code               character varying(10) NOT NULL,
    name               character varying(50) NOT NULL,
    unit_family        character varying(20) NOT NULL,
    multiplier_to_base numeric(18, 8)        NOT NULL,
    CONSTRAINT pk_measurement_units PRIMARY KEY (code),
    CONSTRAINT ck_measurement_units_family CHECK (unit_family IN ('mass', 'area', 'yield', 'count', 'ratio', 'other'))
);

COMMENT ON TABLE ${SCHEMA}.measurement_units
    IS 'PSD Unit_Id lookup. multiplier_to_base converts raw values to base units of MT for mass, hectares for area, and MT per hectare for yield. Units whose conversion depends on the commodity, such as bushels, are classified as other and are not normalized';

CREATE TABLE IF NOT EXISTS ${SCHEMA}.commodity_market_observations
(
    id             bigint                   NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 100000000 CACHE 1 ),
    country_code   character varying(3)     NOT NULL,
    commodity_code character varying(10)    NOT NULL,
    market_year    smallint                 NOT NULL,
    calendar_year  smallint                 NOT NULL,
    month          smallint                 NOT NULL,
    attribute_id   smallint                 NOT NULL,
    unit_code      character varying(10)    NOT NULL,
    value          numeric(18, 4)           NOT NULL,
    value_mt       numeric(18, 4),
    value_hectares numeric(18, 4),
    value_per_ha   numeric(18, 4),
    data_source    character varying(50)    NOT NULL DEFAULT 'USDA_PSD',
    report_date    date,
    loaded_at      timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_commodity_market_observations PRIMARY KEY (id),
    CONSTRAINT uc_commodity_market_obs UNIQUE (
        country_code, commodity_code, market_year, calendar_year, month, attribute_id, unit_code
    ),
    CONSTRAINT ck_commodity_market_obs_month CHECK (month >= 1 AND month <= 12)
);

COMMENT ON TABLE ${SCHEMA}.commodity_market_observations
    IS 'Long-format PSD observations, one row per country, commodity, market year, report month, attribute, and unit';

COMMENT ON COLUMN ${SCHEMA}.commodity_market_observations.value
    IS 'Raw value exactly as reported by the source in unit_code';


ALTER TABLE IF EXISTS ${SCHEMA}.commodities
    ADD CONSTRAINT fk_commodities_parent_code FOREIGN KEY (parent_code)
        REFERENCES ${SCHEMA}.commodities (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_market_observations
    ADD CONSTRAINT fk_commodity_market_observations_country_code FOREIGN KEY (country_code)
        REFERENCES ${SCHEMA}.countries (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_market_observations
    ADD CONSTRAINT fk_commodity_market_observations_commodity_code FOREIGN KEY (commodity_code)
        REFERENCES ${SCHEMA}.commodities (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_market_observations
    ADD CONSTRAINT fk_commodity_market_observations_attribute_id FOREIGN KEY (attribute_id)
        REFERENCES ${SCHEMA}.market_attributes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_market_observations
    ADD CONSTRAINT fk_commodity_market_observations_unit_code FOREIGN KEY (unit_code)
        REFERENCES ${SCHEMA}.measurement_units (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
        NOT VALID;


CREATE UNIQUE INDEX IF NOT EXISTS uc_market_attributes_api_metric_key
    ON ${SCHEMA}.market_attributes (metric_key)
    WHERE include_in_api;

CREATE INDEX IF NOT EXISTS idx_commodity_market_obs_year_commodity_country
    ON ${SCHEMA}.commodity_market_observations (market_year, commodity_code, country_code);

CREATE INDEX IF NOT EXISTS idx_commodity_market_obs_commodity_year_attribute
    ON ${SCHEMA}.commodity_market_observations (commodity_code, market_year, attribute_id);


-- US county-level planted acres (NASS/FSA-style source; not PSD)

CREATE TABLE IF NOT EXISTS ${SCHEMA}.county_crop_planted_acres
(
    id               bigint                   NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 100000000 CACHE 1 ),
    county_fips_code character varying(5)     NOT NULL,
    crop_code        character varying(20)    NOT NULL,
    calendar_year    smallint                 NOT NULL,
    planted_acres    numeric(12, 1)           NOT NULL,
    data_source      character varying(50)    NOT NULL DEFAULT 'USDA_NASS',
    loaded_at        timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_county_crop_planted_acres PRIMARY KEY (id),
    CONSTRAINT uc_county_crop_planted_acres UNIQUE (county_fips_code, crop_code, calendar_year)
);

COMMENT ON TABLE ${SCHEMA}.county_crop_planted_acres
    IS 'US county planted acres by crop and calendar year; crop_code is an API slug such as soybeans, not a PSD commodity code';


-- Bilateral commodity export flows (origin to destination; not PSD totals)

CREATE TABLE IF NOT EXISTS ${SCHEMA}.commodity_export_flows
(
    id                       bigint                   NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 100000000 CACHE 1 ),
    origin_country_code      character varying(3)     NOT NULL,
    destination_country_code character varying(3)     NOT NULL,
    commodity_code           character varying(10)    NOT NULL,
    calendar_year            smallint                 NOT NULL,
    amount                   numeric(18, 1)           NOT NULL,
    data_source              character varying(50)    NOT NULL,
    loaded_at                timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_commodity_export_flows PRIMARY KEY (id),
    CONSTRAINT uc_commodity_export_flows UNIQUE (
        origin_country_code, destination_country_code, commodity_code, calendar_year
    )
);

COMMENT ON TABLE ${SCHEMA}.commodity_export_flows
    IS 'Origin-to-destination export amounts in metric tons; destination ROW is Rest of World';


-- Country socioeconomic indicators (World Bank WDI-style source)

CREATE TABLE IF NOT EXISTS ${SCHEMA}.country_socioeconomic_indicators
(
    id               bigint                   NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 100000000 CACHE 1 ),
    country_code     character varying(3)     NOT NULL,
    calendar_year    smallint                 NOT NULL,
    gdp_per_capita   numeric,
    total_population bigint,
    urban_population bigint,
    data_source      character varying(50)    NOT NULL DEFAULT 'WDI',
    loaded_at        timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_country_socioeconomic_indicators PRIMARY KEY (id),
    CONSTRAINT uc_country_socioeconomic_indicators UNIQUE (country_code, calendar_year)
);

COMMENT ON TABLE ${SCHEMA}.country_socioeconomic_indicators
    IS 'Country-year socioeconomic series for /pdl/countries/{countrycode}/socioeconomic; store PSD country code and query via api_code';


ALTER TABLE IF EXISTS ${SCHEMA}.county_crop_planted_acres
    ADD CONSTRAINT fk_county_crop_planted_acres_county_fips_code FOREIGN KEY (county_fips_code)
        REFERENCES ${SCHEMA}.counties (fips_code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_export_flows
    ADD CONSTRAINT fk_commodity_export_flows_origin_country_code FOREIGN KEY (origin_country_code)
        REFERENCES ${SCHEMA}.countries (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_export_flows
    ADD CONSTRAINT fk_commodity_export_flows_destination_country_code FOREIGN KEY (destination_country_code)
        REFERENCES ${SCHEMA}.countries (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.commodity_export_flows
    ADD CONSTRAINT fk_commodity_export_flows_commodity_code FOREIGN KEY (commodity_code)
        REFERENCES ${SCHEMA}.commodities (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS ${SCHEMA}.country_socioeconomic_indicators
    ADD CONSTRAINT fk_country_socioeconomic_indicators_country_code FOREIGN KEY (country_code)
        REFERENCES ${SCHEMA}.countries (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


CREATE INDEX IF NOT EXISTS idx_county_crop_planted_acres_year_crop
    ON ${SCHEMA}.county_crop_planted_acres (calendar_year, crop_code);

CREATE INDEX IF NOT EXISTS idx_commodity_export_flows_year_commodity_origin
    ON ${SCHEMA}.commodity_export_flows (calendar_year, commodity_code, origin_country_code);

CREATE INDEX IF NOT EXISTS idx_country_socioeconomic_indicators_year
    ON ${SCHEMA}.country_socioeconomic_indicators (calendar_year, country_code);

END;