-- Total-area (GIS) allocation from old CT counties to new planning regions
-- TIGER 2021 counties × TIGER 2024 planning regions; projected EPSG:5070
-- Generated by calculate_ct_weights_from_area.py

INSERT INTO ${SCHEMA}.ct_county_to_region_weights
(old_fips_code, old_county_name, new_fips_code, new_region_name, allocation_weight, method, notes)
VALUES
  ('09001', 'Fairfield', '09909', 'Western CT', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09003', 'Hartford', '09901', 'Capitol', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09007', 'Middlesex', '09903', 'Lower CT River Valley', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09009', 'New Haven', '09907', 'South Central CT', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09011', 'New London', '09908', 'Southeastern CT', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09013', 'Tolland', '09901', 'Capitol', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09015', 'Windham', '09905', 'Northeastern CT', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT')
;
