-- Total-area (GIS) allocation from old CT counties to new planning regions
-- TIGER 2021 counties × TIGER 2024 planning regions
-- Area CRS: EPSG:5070
-- Generated by calculate_ct_weights_from_total_area_gis.py

INSERT INTO ${SCHEMA}.ct_county_to_region_weights
(old_fips_code, old_county_name, new_fips_code, new_region_name, allocation_weight, method, notes)
VALUES
  ('09001', 'Fairfield', '09904', 'Naugatuck Valley', 0.038113, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09001', 'Fairfield', '09909', 'Western CT', 0.961887, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09003', 'Hartford', '09901', 'Capitol', 0.877780, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09003', 'Hartford', '09904', 'Naugatuck Valley', 0.035725, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09003', 'Hartford', '09906', 'Northwest Hills', 0.086494, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09005', 'Litchfield', '09904', 'Naugatuck Valley', 0.127421, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09005', 'Litchfield', '09906', 'Northwest Hills', 0.786781, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09005', 'Litchfield', '09909', 'Western CT', 0.085798, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09007', 'Middlesex', '09903', 'Lower CT River Valley', 1.000000, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09009', 'New Haven', '09901', 'Capitol', 0.000002, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09009', 'New Haven', '09904', 'Naugatuck Valley', 0.281286, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09009', 'New Haven', '09907', 'South Central CT', 0.718712, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09011', 'New London', '09903', 'Lower CT River Valley', 0.101217, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09011', 'New London', '09905', 'Northeastern CT', 0.051547, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09011', 'New London', '09908', 'Southeastern CT', 0.847236, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09013', 'Tolland', '09901', 'Capitol', 0.928510, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09013', 'Tolland', '09905', 'Northeastern CT', 0.071490, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09015', 'Windham', '09905', 'Northeastern CT', 0.946900, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT'),
  ('09015', 'Windham', '09908', 'Southeastern CT', 0.053100, 'total_area_gis', 'GIS area intersection (TIGER 2021 counties × TIGER 2024 planning regions), projected EPSG:5070, Bridgeport merged into Western CT')
;
