-- Cropland-weighted allocation from old CT counties to new planning regions
-- Based on USDA NASS cropland area data (2022)
-- Generated by calculate_ct_weights_from_cropland.py

INSERT INTO ${SCHEMA}.ct_county_to_region_weights
(old_fips_code, old_county_name, new_fips_code, new_region_name, allocation_weight, method, notes)
VALUES
  ('09003', 'Hartford', '09901', 'Capitol', 0.5003, 'cropland_weighted', 'Cropland-weighted allocation (50.0%)'),
  ('09003', 'Hartford', '09906', 'Northwest Hills', 0.4997, 'cropland_weighted', 'Cropland-weighted allocation (50.0%)'),
  ('09005', 'Litchfield', '09906', 'Northwest Hills', 0.6644, 'cropland_weighted', 'Cropland-weighted allocation (66.4%)'),
  ('09005', 'Litchfield', '09909', 'Western CT', 0.3356, 'cropland_weighted', 'Cropland-weighted allocation (33.6%)'),
  ('09009', 'New Haven', '09907', 'South Central CT', 0.3333, 'cropland_weighted', 'Cropland-weighted allocation (33.3%)'),
  ('09009', 'New Haven', '09904', 'Naugatuck Valley', 0.3333, 'cropland_weighted', 'Cropland-weighted allocation (33.3%)'),
  ('09009', 'New Haven', '09903', 'Lower CT River Valley', 0.3333, 'cropland_weighted', 'Cropland-weighted allocation (33.3%)'),
  ('09011', 'New London', '09908', 'Southeastern CT', 0.1247, 'cropland_weighted', 'Cropland-weighted allocation (12.5%)'),
  ('09011', 'New London', '09905', 'Northeastern CT', 0.8753, 'cropland_weighted', 'Cropland-weighted allocation (87.5%)'),
  ('09013', 'Tolland', '09905', 'Northeastern CT', 0.6093, 'cropland_weighted', 'Cropland-weighted allocation (60.9%)'),
  ('09013', 'Tolland', '09901', 'Capitol', 0.3907, 'cropland_weighted', 'Cropland-weighted allocation (39.1%)'),
  ('09015', 'Windham', '09905', 'Northeastern CT', 1.0000, 'cropland_weighted', 'Complete 1:1 mapping')
;
